### ISSUE TITLE
Support for ActiveRecord

### ISSUE THREAD

**Issue by MadBomber** [pgvector/pgvector-ruby#4]
I am attempting to use ActiveRecord against a PG database that has the pg_vector extension.  I have a table that has a field named "embeddings" of type VECTOR.  When I attempt to create a new record in the table using a Ruby Array of Float as the value that I want to put into the embeddings field.  I get a type error in that AR can not typecast my source.

**Comment by ankane** [comment]
Hi @MadBomber, check out [Neighbor](https://github.com/ankane/neighbor) for this.

**Comment by MadBomber** [comment]
Thank you @ankane   I dropped the `pgvector` gem and became neighborly.  program is seeding the db as I type.
